# Generated by Django 4.0.2 on 2022-02-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nagu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('local', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='ramesh',
        ),
    ]
