# Generated by Django 4.0.2 on 2022-02-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=150)),
                ('marks', models.IntegerField(null=True)),
                ('doj', models.DateField(default='1995-06-06')),
            ],
        ),
    ]
